security:
    password_hashers:
        
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Client: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: phoneNumber

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\PhoneNumberAuthenticator
            logout:
                path: app_logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/client/new, roles: PUBLIC_ACCESS }
        - { path: ^/client, roles: ROLE_ADMIN }
        - { path: ^/order/new, roles: ROLE_USER }
        - { path: ^/order, roles: ROLE_ADMIN }
        - { path: ^/dish, roles: ROLE_ADMIN }